### ISSUE TITLE
关于分包

### ISSUE THREAD

**Issue by MinatoHikari** [buhuiming/BleCore#10]
是否可以增加一个包发送前的hook来处理每一个包的数据结构？
参数可以是发送的包整id和第几个分包
这样更方便实现分包协议

**Comment by buhuiming** [comment]
分包是业务层处理，sdk不处理分包、不处理封包和解包

**Comment by MinatoHikari** [comment]
> 分包是业务层处理，sdk不处理分包、不处理封包和解包

问题是sdk也会根据长度截断数据啊，业务层封装如果要知道是第几包如何处理，只能自己按20字节重新分包发了

**Comment by buhuiming** [comment]
sdk对数据包的长度会根据mtu的范围进行拦截，mtu范围通常是23到517字节。业务层分包后要清楚第几包，可以在分包的时候在协议头中增加字段，例如包编号、包标识等。

**Comment by buhuiming** [comment]
dk对数据包的长度会根据mtu的范围进行拦截，mtu范围通常是23到517字节。业务层分包后要清楚第几包，可以在分包的时候在协议头中增加字段，例如包编号、包标识等。
假如mtu设置为500，那每个发送的数据包长度为最大为497（mtu长度包含了ATT的opcode一个字节以及ATT的handle2个字节）。
下图为发送的数据包的协议格式(参考)，业务层在做封包、解包以及组包，可以通过协议中包标识和包编码进行解析。
![image](https://github.com/buhuiming/BleCore/assets/30099293/31ac239d-b490-4222-a85d-243a024fded6)
