### ISSUE TITLE
Android 14兼容性问题

### ISSUE THREAD

**Issue by 704480904** [buhuiming/BleCore#12]
**Google piexl 7a 设备，Android14系统**
设置MTU=23  设备可以正常接收到 拦截抓取的日志也是正常  设置大于23的数字就不行，
默认读取到设备的MTU是247  设置成247之后，写入是成功，
返回的是true 但是设备那边用串口抓包抓到的数据都是空格换行了，
我们需要用BLE发送几kb 的数据 导致无法正常接收，发送几个字节的数据，
一共15包数据，每一包数据写入的都是成功 是否完成也是成功  其他Android设备  Android 10  Android11  Android 12  Android13 都没有出现这个问题
设备可以正常接收到，想请教下大佬，能否帮忙调试一下  多谢

![Screenshot_20231014_181757](https://github.com/buhuiming/BleCore/assets/6984303/e2bed5c5-c40e-44ca-9295-4564370e11b1)

**Comment by buhuiming** [comment]
OK

**Comment by buhuiming** [comment]
暂时没复现此问题，我会持续关注，感谢你的反馈
