### ISSUE TITLE
关于接收大量数据的问题

### ISSUE THREAD

**Issue by vistar1986** [buhuiming/BleCore#14]
作者你好，在使用过程中接收大量数据时会出现数据错乱的问题

![1698811566756](https://github.com/buhuiming/BleCore/assets/11677770/0f3716f0-bc9e-4609-b04c-0b9d5d460d50)

在接收大数据时，onCharacteristicChanged接收的某包数据会延时发出，导致后续组帧错误

**Comment by vistar1986** [comment]
![1698812174289](https://github.com/buhuiming/BleCore/assets/11677770/e16cc27e-e7f0-4f9c-ab1e-683fb47ca7eb)
这是在onCharacteristicChanged中打印日志的地方，打印日志前没有做任何耗时操作

**Comment by buhuiming** [comment]
麻烦更新到v1.5.0，把日志去掉再试试看

**Comment by vistar1986** [comment]
> 麻烦更新到v1.5.0，把日志去掉再试试看

已经升级到v1.5.0，并且把日志关闭，还是会出现问题~

![screenshot1698898226083](https://github.com/buhuiming/BleCore/assets/11677770/03bc0493-5cdc-4a2c-a4f3-39725d5ab8a3)
![Screenshot_20231102_120946](https://github.com/buhuiming/BleCore/assets/11677770/4a250371-d531-4314-ac25-ecb3b0f30269)

以下为导入代码
![1698898321072](https://github.com/buhuiming/BleCore/assets/11677770/8e991d05-0ff9-496f-9edc-d43348f70c52)
![image](https://github.com/buhuiming/BleCore/assets/11677770/ffd09620-bc9f-43da-8ba1-c1026b8e8071)

**Comment by buhuiming** [comment]
我大概知道什么原因了，onCharacteristicChanged被指定在IO线程，子线程不保证顺序。我已经去掉IO线程的指定，如果有需要在IO线程处理，业务端自行处理。
请更新1.5.1

**Comment by buhuiming** [comment]
我大概知道什么原因了，onCharacteristicChanged被指定在IO线程，子线程不保证顺序。我已经去掉IO线程的指定，如果有需要在IO线程处理，业务端自行处理。
请更新1.5.1

**Comment by vistar1986** [comment]
> 我大概知道什么原因了，onCharacteristicChanged被指定在IO线程，子线程不保证顺序。我已经去掉IO线程的指定，如果有需要在IO线程处理，业务端自行处理。 请更新1.5.1

你好，在更新新版后，数据暂时没有出现错乱的情况，我会持续测试，感谢作者大大

**Comment by buhuiming** [comment]
好的，感谢你的反馈
