### ISSUE TITLE
无法搜索到经典蓝牙设备

### ISSUE THREAD

**Issue by gaoguanqi** [buhuiming/BleCore#22]

**Comment by buhuiming** [comment]
BLE（低功耗蓝牙）和经典蓝牙是两个不同的协议。BLE使用的是BluetoothLeScanner进行扫描，而经典蓝牙使用的是BluetoothAdapter进行扫描。这个组件是针对低功耗蓝牙，不是经典蓝牙

**Comment by gaoguanqi** [comment]
所以大佬，有考虑增加经典蓝牙的扫描和通信吗

**Comment by buhuiming** [comment]
这个组件是针对低功耗蓝牙，所以不考虑经典蓝牙
