### ISSUE TITLE
autoconnect

### ISSUE THREAD

**Issue by YuHsiang0120** [buhuiming/BleCore#24]
要使用autoconnect是否需要先和裝置配對
以及 非主動斷開自動連接的非主動 是建立在什麼樣的情況

**Comment by lipengdeGit** [comment]
ble  设备   不需要配对  扫描到 点连接 就能直接连上

**Comment by buhuiming** [comment]
不推荐使用autoconnect，autoconnect没能区别手动断开，建议自行添加重连机制；
主动断开指的是调用了disConnect()方法；非主动断开包含：设备断电或关机、设备超出距离等
