### ISSUE TITLE
isForceConnect的作用和解释没明白

### ISSUE THREAD

**Issue by cxf910714** [buhuiming/BleCore#25]
我可不可以理解无论是isForceConnect 还是AutoConnect还是无法在蓝牙断开后进行自动重连，
我在测试的时候连接成功后，设备蓝牙断电后，间隔2S后马上开启，DEMO不会进行重连处理，
还是需要自己去在监听地方处理重连逻辑

**Comment by buhuiming** [comment]
AutoConnect是Gatt没有被close之前，会尝试重连；如果close之后，就不生效了。建议重连在业务层(disconnect)处理;

**Comment by buhuiming** [comment]
isForceConnect，为true；不管设备是否是已连接状态，都会调用device.connectGatt方法。这个字段主要是处理有些机型出现，BleCore接收到disconnect后，未调用gatt的close之前，触发了已连接状态，BleCore的连接状态和系统的连接状态不一致的情况下。
