### ISSUE TITLE
连接慢的问题

### ISSUE THREAD

**Issue by chengxinping** [buhuiming/BleCore#27]
同一个手机，同一个蓝牙设备，用fastble和本库连接，测试多次均发现连接、读写。通知全流程都会慢5~6s，还有优化的空间吗

**Comment by buhuiming** [comment]
并未遇到所描述的问题，检查一下配置项是否合理。

**Comment by buhuiming** [comment]
![image](https://github.com/buhuiming/BleCore/assets/30099293/8e0bb8e1-aab8-4a8a-9d4c-af46d7205b65) 整个过程3.5s

**Comment by buhuiming** [comment]
![image](https://github.com/buhuiming/BleCore/assets/30099293/a507b9f8-d722-40c2-a375-df4644e2ca72)
