### ISSUE TITLE
为什么大于等于Android S还需要位置权限

### ISSUE THREAD

**Issue by zdxiang** [buhuiming/BleCore#32]
你的模板不适合我

**Comment by buhuiming** [comment]
Android S蓝牙权限适配我没有做得很详细，如果不需要位置信息，可以不用位置权限，如果需要请Fork修改

**Comment by zdxiang** [comment]
> Android S蓝牙权限适配我没有做得很详细，如果不需要位置信息，可以不用位置权限，如果需要请Fork修改

好的，我已自行解决。建议把权限判断这块抛给使用者。
 `    fun startScan(
        scanMillisTimeOut: Long?,
        scanRetryCount: Int?,
        scanRetryInterval: Long?,
        bleScanCallback: BleScanCallback
    ) {
       // if (!BleUtil.isPermission(getBleManager().getContext())) {
       //     bleScanCallback.callScanFail(BleScanFailType.NoBlePermission)
       //     return
       //}
        initScannerAndStart(
            scanMillisTimeOut,
            scanRetryCount,
            scanRetryInterval,
            bleScanCallback
        )
    }`

**Comment by buhuiming** [comment]
好的
