### ISSUE TITLE
公司的设备，华为手机无法read，显示超时

### ISSUE THREAD

**Issue by Yuanarcheannovice** [buhuiming/BleCore#35]
问题描述(出现的环境，demo是否存在)【必填】
直接跑的demo，连公司设备，connect，notify没问题，read，就超时；
https://github.com/wandersnail/easyble-x  这个sdk，链接公司设备后，read没有问题，你可以参考一下read部分代码；

框架文档是否提及了该问题【必答】
无

是否已经查阅框架文档但还未能解决的【必答】
看文档了，用的是demo;

issue 列表中是否有人曾提过类似的问题【必答】
无；

是否已经搜索过了 issue 列表但还未能解决的【必答】
yes；

![1713495711267](https://github.com/buhuiming/BleCore/assets/18046524/24332452-9a22-47dc-836f-8b1aabdf2fcd)

![1713497011467](https://github.com/buhuiming/BleCore/assets/18046524/66555b46-1758-4973-bd9e-48b71b178a5e)

**Comment by buhuiming** [comment]
感谢反馈！代码是一样的，SDK版本不一样。 我找机子看能否复现一下，方便的话，麻烦帮忙定位一下onCharacteristicRead方法有无触发，demo没怎么更新了

**Comment by buhuiming** [comment]
已修复，请更新v2.1.3
