### ISSUE TITLE
关于扫描蓝牙权限问题

### ISSUE THREAD

**Issue by 704480904** [buhuiming/BleCore#36]
想请教下扫描蓝牙权限 的问题 扫描蓝牙是否一定要开精确位置权限 用户选择了大致位置是否就无法扫描到蓝牙设备 TargetSDK  为33  测试机为Android 14 的三星 因为蓝牙权限被很多用户投诉

**Comment by 704480904** [comment]
不不不，我的意思是，如果不用精确位置 能否扫描到蓝牙设备 因为我目前发现用粗略位置扫描不到

**Comment by buhuiming** [comment]
经过测试，发现没有注册精准位置权限，有些机子是扫描不到设备的

**Comment by buhuiming** [comment]
这个问题我们在很多款产品中出现了，经过确认才加上精准位置权限的。不过我可以取消精准位置权限的注册、申请和判断，由业务端去处理

**Comment by buhuiming** [comment]
取消精准位置权限，会影响部分机型Ble扫描不到设备，但不影响连接、读数据、写数据等

**Comment by 704480904** [comment]
如果我用经典蓝牙 我的APP里面 只有SPP  好像也是扫描不到蓝牙设备 Android 14 是否是一定要开精确位置 国外用户对用户权限很敏感 因为这个问题被投诉很多次，我加你QQ了，大佬
