### ISSUE TITLE
提醒作者可以把 friendly DeviceName 的获取集成进来

### ISSUE THREAD

**Issue by sharpidea** [buhuiming/BleCore#37]
可通过
    public static final UUID GENERIC_ACCESS_SERVICE_UUID = UUID.fromString("00001800-0000-1000-8000-00805f9b34fb");
    public static final UUID GENERIC_ACCESS_DEVICE_NAME_UUID = UUID.fromString("00002a00-0000-1000-8000-00805f9b34fb");
 获取

**Comment by buhuiming** [comment]
在哪部分使用到？

**Comment by sharpidea** [comment]
给用户显示蓝牙列表的时候，friendly name 会更有辨识度，甚至某些设备这个名字是用户自己起的，如果没有的话，很多设备的默认名字是无意义的码甚至为null
如果能加上就最好了， python 的 simpleble 可以直接 scan 出来， ios 的 coreble 也可以直接 scan 出来

**Comment by buhuiming** [comment]
考虑到BleCore扫描的时候要解析蓝牙广播，业务层可能也会对蓝牙广播进行二次解析，所以没加上。BleDevice里面可以拿到广播协议包，业务层可自行扩展处理。
