### ISSUE TITLE
为什么对一个设备已经开了通知了，去其他activity监听这数据，还需要开通知才行

### ISSUE THREAD

**Issue by strongerzzx** [buhuiming/BleCore#39]
感觉蓝牙的通知是不是只要打开了，就不用频繁的notify？能不能把获取蓝牙返回给app的数据跟打开蓝牙的通知进行分离？

**Comment by buhuiming** [comment]
小伙子，notify可以在连接成功之后设置，使用观察者模式或者全局对象去接受和分发数据。使用观察者模式最佳。
