### ISSUE TITLE
多连接问题

### ISSUE THREAD

**Issue by Android-wangmeng** [buhuiming/BleCore#4]
请问多连接的通知回调怎么处理呢，回调函数里面有没device,只有数据。

**Comment by buhuiming** [comment]
每个BleDevice对应一个BleNotifyCallback

**Comment by buhuiming** [comment]
每个BleDevice的每个特征值对应一个BleNotifyCallback

**Comment by Android-wangmeng** [comment]
多个设备调用notify，BleDevice不一样，回调的时候我是直接拿方法里的BleDevice来判断是哪个设备的notify吗

**Comment by buhuiming** [comment]
是的。
