### ISSUE TITLE
可以设置特征的writeType吗？

### ISSUE THREAD

**Issue by licoba** [buhuiming/BleCore#41]
我有一个特征，他可以是 `WRITE_TYPE_DEFAULT `的 也可以是`WRITE_TYPE_NO_RESPONSE` 的
（也就是有响应和无响应）但是在demo app上面显示，他是write类型的，默认是有响应的写入。
我找了很久没找到可以设置Write类型的，目前只能通过有响应的方式来写入，这样速度很慢。
可以设置特征的writeType为 `WRITE_TYPE_NO_RESPONSE` 吗?

**Comment by buhuiming** [comment]
如果特征值支持WRITE_TYPE_NO_RESPONSE，那么就会选择WRITE_TYPE_NO_RESPONSE，可以看一下源码

**Comment by licoba** [comment]
如果两个都支持，我怎么手动设置`WRITE_TYPE_DEFAULT ` 或者是  `WRITE_TYPE_NO_RESPONSE` 其中的一个呢？

**Comment by buhuiming** [comment]
后续可以添加上
