### ISSUE TITLE
onCharacteristicChanged接收到的data数据被截断

### ISSUE THREAD

**Issue by zhangcaibing** [buhuiming/BleCore#42]
![image](https://github.com/user-attachments/assets/f12f0076-78cd-4ec4-a08d-ff3047de242b)

如图，一条完整的蓝牙返回数据格式：ff 30 33 36 31 00 00 00 00 00 fe，但实际在收到的数据中会出现各种的数据被截断，我不知道是少设置参数导致还是什么原因？蓝牙返回发每次发送数据是一条完整的数据格式，收到就会各种各样的数据，还存在部分数据丢失问题。

**Comment by buhuiming** [comment]
mtu设置多少？

**Comment by buhuiming** [comment]
![image](https://github.com/user-attachments/assets/6de873ef-db04-45e4-b266-4900263696f6)
