### ISSUE TITLE
概率性出现任务队列没有执行就移除

### ISSUE THREAD

**Issue by zpliang94** [buhuiming/BleCore#48]
问题描述(出现的环境，demo是否存在)
demo没有出现，一次性进行了10来次写任务，有小概率出现

框架文档是否提及了该问题【必答】
没有
是否已经查阅框架文档但还未能解决的【必答】
是的
issue 列表中是否有人曾提过类似的问题【必答】
没有
是否已经搜索过了 issue 列表但还未能解决的【必答】
未能解决

图片中第4个任务BleTask@eacb996 没有进行写数据就被移除了，这问题小概率出现
![WechatIMG290](https://github.com/user-attachments/assets/de0aab67-eb7e-4b49-a11d-31657245c3ed)
![WechatIMG291](https://github.com/user-attachments/assets/ed2f938f-3125-4e15-9fa7-2ca371a53fb1)

**Comment by buhuiming** [comment]
你是通过什么代码来触发发送数据的，看日志是因为有2个数据包，通过getTaskId来生成了两个一样的taskid导致的

**Comment by zpliang94** [comment]
使用 BleManager.get().writeData()  发送数据，调用了十多个数据包 。
现在使用 BleManager.get().writeQueueData(mBleDevice, KeyUtils.UUID_SERVICE_E, KeyUtils.UUID_WRITE, byteArray, retryWriteCount = 1 ) 方法就没出现过这情况。 @buhuiming

**Comment by zpliang94** [comment]
for循环调用 BleManager.get().writeData() 发送数据

**Comment by buhuiming** [comment]
好的，不建议for循环调用BleManager.get().writeData() ，这个方法是支持传递数据集合的

**Comment by zpliang94** [comment]
连续调用 BleManager.get().writeQueueData()，BleManager.get().writeQueueData()，BleManager.get().writeQueueData()  还是会出现taskId 一样，有些指令没有发送就被移除

**Comment by zpliang94** [comment]
主要原因是生成的时间戳是一样

**Comment by zpliang94** [comment]
@buhuiming id还是一样的
![1729238639271](https://github.com/user-attachments/assets/601f31cf-ebd0-4db7-b6f4-7ec6dc69ce20)

![1729238538251](https://github.com/user-attachments/assets/1a0fb8d7-b208-4b63-a94b-1223cf4335ca)


![1729238182317](https://github.com/user-attachments/assets/72e07599-acd9-42df-a99c-029d00d99e25)

**Comment by zpliang94** [comment]
更新了v2.3.1版本，连续调用 BleManager.get().writeQueueData() 三次，BleConnectedDevice.writeQueueData() 方法中id不一样，bleWriteRequest?.writeQueueData() 的taskId只以第一次为id @buhuiming

**Comment by zpliang94** [comment]
第二次使用writeQueueData()的id还是为第一次writeQueueData()的id 1859999209893252jRY8

**Comment by buhuiming** [comment]
你先用writeData方法，这个应该没问题。我再看看writeQueueData

**Comment by buhuiming** [comment]
找到原因了，下周我调试修复再更新

**Comment by zpliang94** [comment]
重看了第一次提交问题的log，好像不是taskid相同的原因

**Comment by zpliang94** [comment]
还有一个可能点是 operateInterval ，设置200时候也容易出现没有执行就移除

**Comment by buhuiming** [comment]
请更新到v2.3.2再试试
