### ISSUE TITLE
调用connect方法会中断扫描

### ISSUE THREAD

**Issue by xiaojigugu** [buhuiming/BleCore#49]
首先，感谢作者！
请问有什么办法可以在发起连接时不中断扫描吗？
在多设备连接场景中，设备被扫描到的时间是随机，需要保持扫描持续进行，而不是在连接时就停止扫描。
目前，我是在connect的回调中重新开启扫描来保证能及时发现其他蓝牙设备。

**Comment by buhuiming** [comment]
![image](https://github.com/user-attachments/assets/e93a8e1d-126d-4c6c-88f4-35c0519b5647)
请更新到v2.3.2，添加属性stopScanWhenStartConnect，支持连接时可以继续扫描，该值默认为true，请设置为false即可
